isil2sameAs = {
    "(DE-627)": "http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=",
    "DE-627": "http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=",
    # "DE-576":"http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=",
    # "(DE-576)":"http://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=",
    "DE-588": "https://d-nb.info/gnd/",
    "(DE-588)": "https://d-nb.info/gnd/",
    "DE-601": "http://gso.gbv.de/PPN?PPN=",
    "(DE-601)": "http://gso.gbv.de/PPN?PPN=",
    "DE-15": "Univeristätsbibliothek Leipzig",
    "DE-14": "Sächsische Landesbibliothek – Staats- und Universitätsbibliothek Dresden",
}


map_entities = {
    "p": "persons",  # Personen, individualisiert
    "n": "persons",  # Personen, namen, nicht individualisiert
    "s": "topics",  # Schlagwörter/Berufe
    "b": "organizations",  # Organisationen
    "g": "geo",  # Geographika
    "u": "works",  # Werktiteldaten
    "f": "events"
}

map_types = {
    "p": "Person",  # Personen, individualisiert
    "n": "Person",  # Personen, namen, nicht individualisiert
    "s": "Thing",  # Schlagwörter/Berufe
    "b": "Organization",  # Organisationen
    "g": "Place",  # Geographika
    "u": "CreativeWork",  # Werktiteldaten
    "f": "Event"
}

marc2relation = {
    "VD-16 Mitverf": "contributor",
    "v:Mitverf": "contributor",
    "v:Co-Autor": "contributor",
    "v:Doktorvater": "contributor",
    "v:Illustrator": "contributor",
    "v:Übersetzer": "contributor",
    "v:Biograf": "contributor",
    "v:Förderer": "contributor",
    "v:Berater": "contributor",
    "v:hrsg": "contributor",
    "v:Mitautor": "contributor",
    "v:Partner": "contributor",
    
    "v:Tocher": "children",            #several typos in SWB dataset
    "tochter": "children",
    "Z:Tochter":"children",
    "Sohn": "children",
    "v:Nachkomme": "children",
    "v:zweites Kind": "children",
    
    "v:Erste Ehefrau":"spouse",
    "v:Zweite Ehefrau":"spouse",
    "v:Gattin": "spouse",
    "v:Gatte": "spouse",
    "v:Gemahl": "spouse",
    "Ehe": "spouse",
    "Frau": "spouse",
    "Mann": "spouse",
    
    "v:Jüngster Bruder": "sibling",
    "Bruder": "sibling",
    "v:Zwilling": "sibling",
    "Schwester": "sibling",
    "v:Halbschwester": "sibling",
    "v:Halbbruder": "sibling",
    "Vater": "parent",
    "Z:Vater":"parent",
    "v:Stiefvater": "parent",
    "Mutter": "parent",
    
    "Nachfolger": "follows",
    "Vorgänger": "follows",
    
    "v:Vorfahr": "relatedTo",
        
    "v:Schüler": "relatedTo",        
    "Lehrer": "relatedTo",        
    "v:frühere Ehefrau": "relatedTo",
    "v:Schwager": "relatedTo",        
    "v:Ur": "relatedTo",          
    "v:Muse": "relatedTo",
    "v:Nachfahre": "relatedTo",         
    "v:Groß": "relatedTo",    
    "v:Langjähriger Geliebter": "relatedTo",    
    "v:Lebensgefährt": "relatedTo",    
    "v:Nichte": "relatedTo",
    "v:Stiefnichte": "relatedTo",
    "v:Neffe": "relatedTo",
    "v:Onkel": "relatedTo",
    "v:Tante": "relatedTo",
    "v:Verlobt": "relatedTo",
    "v:Vorfahren": "relatedTo",
    "v:Vetter": "relatedTo",
    "v:Tauf": "relatedTo",
    "v:Pate": "relatedTo",
    "v:Schwägerin": "relatedTo",
    "v:Schwiegervater": "relatedTo",
    "v:Schwiegermutter": "relatedTo",
    "v:Schwiegertochter": "relatedTo",
    "v:Schwiegersohn": "relatedTo",
    "v:Enkel": "relatedTo",
    "v:Mätresse": "relatedTo",
    "Freund": "knows",
    "v:Großvater": "relatedTo",
    "v:Cousin": "relatedTo",
    "v:Lebenspartner": "relatedTo",
    "v:Berater und Freund": "relatedTo",
    "v:Geliebte": "relatedTo",
    "v:Modell und Lebensgefährtin":"relatedTo",
    "v:Liebesbeziehung":"relatedTo",
    
    "v:publizistische Zusammenarbeit und gemeinsame öffentliche Auftritte": "colleague",
    "v:Sekretär": "colleague", 
    "v:Privatsekretär": "colleague", 
    "v:Kolleg": "colleague", 
    "v:Mitarbeiter": "colleague", 
    "v:Kommilitone": "colleague", 
    "v:Zusammenarbeit mit": "colleague", 
    "v:gemeinsames Atelier": "colleague", 
    "v:Geschäftspartner": "colleague" , 
    "v:musik. Partnerin": "colleague" ,
    "v:Künstler. Partner": "colleague" ,  
    "assistent": "colleague",
    
    #see also http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/inhaltserschliessung/gndCodes.pdf?__blob=publicationFile
    "adel":"honorificPrefix",
    "adre":"recipent",
    "adue":"parentOrganization",
    "affi":"affiliation",
    #"akad":"honorificPrefix",
    "akti":"hasProfession",
    "bezf":"relatedTo",
    "bezb":"colleague",
    "beza":"knows",
    "bete": "contributor",
    "rela":"knows",
    "affi":"knows",
    "aut1":"author",
}


rolemapping={
"abr":"KürzendeR",
"acp":"HerstellerIn von Nachbildungen",
"act":"SchauspielerIn",
"adi":"Art Director",
"adp":"BearbeiterIn",
"aft":"VerfasserIn eines Nachworts",
"anl":"AnalytikerIn",
"anm":"TrickfilmzeichnerIn",
"ann":"KommentatorIn",
"ant":"BibliographischeR VorgängerIn",
"ape":"BerufungsbeklagteR/RevisionsbeklagteR",
"apl":"BerufungsklägerIn/RevisionsklägerIn",
"app":"AntragstellerIn",
"aqt":"AutorIn von Zitaten oder Textabschnitten",
"arc":"ArchitektIn",
"ard":"künstlerische Leitung",
"arr":"ArrangeurIn",
"art":"KünstlerIn",
"asg":"RechtsnachfolgerIn",
"asn":"zugehöriger Name",
"ato":"AutographIn",
"att":"zugehöriger Name",
"auc":"AuktionatorIn",
"aud":"AutorIn des Dialogs",
"aui":"VerfasserIn eines Geleitwortes",
"aus":"DrehbuchautorIn",
"aut":"VerfasserIn",
"bdd":"BindungsgestalterIn",
"bjd":"EinbandgestalterIn",
"bkd":"BuchgestalterIn",
"bkp":"BuchherstellerIn",
"blw":"AutorIn des Klappentextes",
"bnd":"BuchbinderIn",
"bpd":"GestalterIn des Exlibris",
"brd":"Sender",
"brl":"BrailleschriftprägerIn",
"bsl":"BuchhändlerIn",
"cas":"FormgießerIn",
"ccp":"konzeptionelle Leitung",
"chr":"ChoreografIn",
"clb":"MitarbeiterIn",
"cli":"KlientIn, AuftraggeberIn",
"cll":"KalligrafIn",
"clr":"KoloristIn",
"clt":"LichtdruckerIn",
"cmm":"KommentatorIn",
"cmp":"KomponistIn",
"cmt":"SchriftsetzerIn",
"cnd":"DirigentIn",
"cng":"Kameramann/frau",
"cns":"ZensorIn",
"coe":"BerufungsbeklagteR im streitigen Verfahren",
"col":"SammlerIn",
"com":"ZusammenstellendeR",
"con":"KonservatorIn",
"cor":"SammlungskuratorIn",
"cos":"AnfechtendeR, bestreitende Partei",
"cot":"BerufungsklägerIn im streitigen Verfahren",
"cou":"zuständiges Gericht",
"cov":"UmschlaggestalterIn",
"cpc":"BeansprucherIn des Urheberrechts",
"cpe":"BeschwerdeführerIn-BerufungsbeklagteR",
"cph":"InhaberIn des Urheberrechts",
"cpl":"BeschwerdeführerIn/KlägerIn",
"cpt":"KlägerIn/BerufungsklägerIn",
"cre":"GeistigeR SchöpferIn",
"crp":"KorrespondentIn",
"crr":"KorrektorIn",
"crt":"GerichtsstenografIn",
"csl":"BeraterIn",
"csp":"ProjektberaterIn",
"cst":"KostümbildnerIn",
"ctb":"MitwirkendeR",
"cte":"AnfechtungsgegnerIn-BerufungsbeklagteR",
"ctg":"KartografIn",
"ctr":"VertragspartnerIn",
"cts":"AnfechtungsgegnerIn",
"ctt":"AnfechtungsgegnerIn-BerufungsklägerIn",
"cur":"KuratorIn",
"cwt":"KommentatorIn",
"dbp":"Erscheinungsort",
"dfd":"AngeklagteR/BeklagteR",
"dfe":"AngeklagteR/BeklagteR-BerufungsbeklagteR",
"dft":"AngeklagteR/BeklagteR-BerufungsklägerIn",
"dgg":"Grad-verleihende Institution",
"dgs":"AkademischeR BetreuerIn",
"dir":"Dirigent",
"dis":"PromovierendeR",
"dln":"VorzeichnerIn",
"dnc":"TänzerIn",
"dnr":"GeldgeberIn",
"dpc":"AbgebildeteR",
"dpt":"AnlegerIn",
"drm":"TechnischeR ZeichnerIn",
"drt":"RegisseurIn",
"dsr":"DesignerIn",
"dst":"Vertrieb",
"dtc":"BereitstellerIn von Daten",
"dte":"WidmungsempfängerIn",
"dtm":"DatenmanagerIn",
"dto":"WidmendeR",
"dub":"angeblicheR AutorIn",
"edc":"BearbeiterIn der Zusammenstellung",
"edm":"CutterIn",
"edt":"HerausgeberIn",
"egr":"StecherIn",
"elg":"ElektrikerIn",
"elt":"GalvanisiererIn",
"eng":"IngenieurIn",
"enj":"Normerlassende Gebietskörperschaft",
"etr":"RadiererIn",
"evp":"Veranstaltungsort",
"exp":"ExperteIn",
"fac":"FacsimilistIn",
"fds":"Filmvertrieb",
"fld":"BereichsleiterIn",
"flm":"BearbeiterIn des Films",
"fmd":"FilmregisseurIn",
"fmk":"FilmemacherIn",
"fmo":"frühereR BesitzerIn",
"fmp":"FilmproduzentIn",
"fnd":"GründerIn",
"fpy":"Erste Partei",
"frg":"FälscherIn",
"gis":"GeographIn",
"grt":"GraphischeR TechnikerIn",
"hg":"Herausgeber",
"his":"Gastgebende Institution",
"hnr":"GefeierteR",
"hst":"GastgeberIn",
"Ill":"Illustrator",
"ill":"IllustratorIn",
"ilu":"Illuminator, BuchmalerIn",
"ins":"InserierendeR",
"inv":"ErfinderIn",
"isb":"Herausgebendes Organ",
"itr":"InstrumentalmusikerIn",
"ive":"InterviewteR",
"ivr":"InterviewerIn",
"jud":"RichterIn",
"jug":"zuständige Gerichtsbarkeit",
"kad":"Kadenzverfasser",
"lbr":"Labor",
"lbt":"LibrettistIn",
"ldr":"Laborleitung",
"led":"Führung",
"lee":"Libelee-appellee",
"lel":"BeklagteR im Seerecht/Kirchenrecht",
"len":"LeihgeberIn",
"let":"Libelee-appellant",
"lgd":"LichtgestalterIn",
"lie":"Libelant-appellee",
"lil":"KlägerIn im Seerecht/Kirchenrecht",
"lit":"Libelant-appellant",
"lsa":"LandschaftsarchitektIn",
"lse":"LizenznehmerIn",
"lso":"LizenzgeberIn",
"ltg":"LithographIn",
"lyr":"TextdichterIn",
"mcp":"ArrangeurIn, Notenleser/-schreiberIn",
"mdc":"Metadatenkontakt",
"med":"Medium",
"mfp":"Herstellungsort",
"mfr":"HerstellerIn",
"mod":"ModeratorIn",
"mon":"BeobachterIn",
"mrb":"MarmorarbeiterIn, MarmoriererIn",
"mrk":"Markup-EditorIn",
"msd":"MusikalischeR LeiterIn",
"mte":"Metall-GraveurIn",
"mtk":"ProtokollantIn",
"mus":"MusikerIn",
"nrt":"ErzählerIn",
"opn":"GegnerIn",
"org":"UrheberIn",
"orm":"VeranstalterIn",
"osp":"On-screen PräsentatorIn",
"oth":"BerichterstatterIn",
"own":"BesitzerIn",
"pan":"DiskussionsteilnehmerIn",
"pat":"SchirmherrIn",
"pbd":"Verlagsleitung",
"pbl":"Verlag",
"pdr":"Projektleitung",
"pfr":"Korrektur",
"pht":"FotografIn",
"plt":"DruckformherstellerIn",
"pma":"Genehmigungsstelle",
"pmn":"Produktionsleitung",
"pop":"PlattendruckerIn",
"ppm":"PapiermacherIn",
"ppt":"PuppenspielerIn",
"pra":"Praeses",
"prc":"Prozesskontakt",
"prd":"Produktionspersonal",
"pre":"PräsentatorIn",
"prf":"AusführendeR",
"prg":"ProgrammiererIn",
"prm":"DruckgrafikerIn",
"prn":"Produktionsfirma",
"pro":"ProduzentIn",
"prp":"Produktionsort",
"prs":"SzenenbildnerIn",
"prt":"DruckerIn",
"prv":"AnbieterIn",
"pta":"PatentanwärterIn",
"pte":"KlägerIn-BerufungsbeklagteR",
"ptf":"ZivilklägerIn",
"pth":"PatentinhaberIn",
"ptt":"KlägerIn-BerufungsklägerIn",
"pup":"Veröffentlichungsort",
"rbr":"RubrikatorIn",
"rcd":"TonmeisterIn",
"rce":"ToningenieurIn",
"rcp":"AdressatIn",
"rdd":"HörfunkregisseurIn",
"Red":"Redakteur",
"red":"RedakteurIn",
"ren":"RendererIn (Bildverarbeitung)",
"res":"ForscherIn",
"rev":"RezensentIn, GutachterIn",
"rpc":"HörfunkproduzentIn",
"rps":"Aufbewahrungsort, TreuhänderIn",
"rpt":"ReporterIn",
"rpy":"Verantwortliche Partei",
"rse":"AntragsgegnerIn-BerufungsbeklagteR",
"rsg":"RegisseurIn der Wiederaufführung",
"rsp":"RespondentIn",
"rsr":"RestauratorIn",
"rst":"AntragsgegnerIn-BerufungsklägerIn",
"rth":"Leitung des Forschungsteams",
"rtm":"Mitglied des Forschungsteams",
"sad":"WissenschaftlicheR BeraterIn",
"sce":"DrehbuchautorIn",
"scl":"BildhauerIn",
"scr":"SchreiberIn",
"sds":"Tongestalter",
"sec":"SekretärIn",
"sgd":"BühnenregisseurIn",
"sgn":"UnterzeichnerIn",
"sht":"Unterstützender Veranstalter",
"sll":"VerkäuferIn",
"sng":"SängerIn",
"spk":"RednerIn",
"spn":"SponsorIn",
"spy":"Zweite Partei",
"srv":"LandvermesserIn",
"std":"BühnenbildnerIn",
"stg":"Kulisse",
"stl":"GeschichtenerzählerIn",
"stm":"InszenatorIn",
"stn":"Normungsorganisation",
"str":"StereotypeurIn",
"tcd":"Technische Leitung",
"tch":"LehrerIn",
"ths":"BetreuerIn (Doktorarbeit)",
"tld":"FernsehregisseurIn",
"tlp":"FernsehproduzentIn",
"trc":"TranskribiererIn",
"trl":"ÜbersetzerIn",
"tyd":"Schrift-DesignerIn",
"tyg":"SchriftsetzerIn",
"uvp":"Hochschulort",
"vac":"SynchronsprecherIn",
"vdg":"BildregisseurIn",
"voc":"VokalistIn",
"wac":"KommentarverfasserIn",
"wal":"VerfasserIn von zusätzlichen Lyrics",
"wam":"AutorIn des Begleitmaterials",
"wat":"VerfasserIn von Zusatztexten",
"wdc":"HolzschneiderIn",
"wde":"HolzschnitzerIn",
"win":"VerfasserIn einer Einleitung",
"wit":"ZeugeIn",
"wpr":"VerfasserIn eines Vorworts",
"wst":"VerfasserIn von ergänzendem Text"
}


rolemapping_en = {
"abr": "Abridger",
"acp": "Art copyist",
"act": "Actor",
"adi": "Art director",
"adp": "Adapter",
"aft": "Author of afterword, colophon, etc.",
"anl": "Analyst",
"anm": "Animator",
"ann": "Annotator",
"ant": "Bibliographic antecedent",
"ape": "Appellee",
"apl": "Appellant",
"app": "Applicant",
"aqt": "Author in quotations or text abstracts",
"arc": "Architect",
"ard": "Artistic director",
"arr": "Arranger",
"art": "Artist",
"asg": "Assignee",
"asn": "Associated name",
"ato": "Autographer",
"att": "Attributed name",
"auc": "Auctioneer",
"aud": "Author of dialog",
"aui": "Author of introduction, etc.",
"aus": "Screenwriter",
"aut": "Author",
"bdd": "Binding designer",
"bjd": "Bookjacket designer",
"bkd": "Book designer",
"bkp": "Book producer",
"blw": "Blurb writer",
"bnd": "Binder",
"bpd": "Bookplate designer",
"brd": "Broadcaster",
"brl": "Braille embosser",
"bsl": "Bookseller",
"cas": "Caster",
"ccp": "Conceptor",
"chr": "Choreographer",
"-clb": "Collaborator",
"cli": "Client",
"cll": "Calligrapher",
"clr": "Colorist",
"clt": "Collotyper",
"cmm": "Commentator",
"cmp": "Composer",
"cmt": "Compositor",
"cnd": "Conductor",
"cng": "Cinematographer",
"cns": "Censor",
"coe": "Contestant-appellee",
"col": "Collector",
"com": "Compiler",
"con": "Conservator",
"cor": "Collection registrar",
"cos": "Contestant",
"cot": "Contestant-appellant",
"cou": "Court governed",
"cov": "Cover designer",
"cpc": "Copyright claimant",
"cpe": "Complainant-appellee",
"cph": "Copyright holder",
"cpl": "Complainant",
"cpt": "Complainant-appellant",
"cre": "Creator",
"crp": "Correspondent",
"crr": "Corrector",
"crt": "Court reporter",
"csl": "Consultant",
"csp": "Consultant to a project",
"cst": "Costume designer",
"ctb": "Contributor",
"cte": "Contestee-appellee",
"ctg": "Cartographer",
"ctr": "Contractor",
"cts": "Contestee",
"ctt": "Contestee-appellant",
"cur": "Curator",
"cwt": "Commentator for written text",
"dbp": "Distribution place",
"dfd": "Defendant",
"dfe": "Defendant-appellee",
"dft": "Defendant-appellant",
"dgc": "Degree committee member",
"dgg": "Degree granting institution",
"dgs": "Degree supervisor",
"dis": "Dissertant",
"dln": "Delineator",
"dnc": "Dancer",
"dnr": "Donor",
"dpc": "Depicted",
"dpt": "Depositor",
"drm": "Draftsman",
"drt": "Director",
"dsr": "Designer",
"dst": "Distributor",
"dtc": "Data contributor",
"dte": "Dedicatee",
"dtm": "Data managerv",
"dto": "Dedicator",
"dub": "Dubious author",
"edc": "Editor of compilation",
"edm": "Editor of moving image work",
"edt": "Editor",
"egr": "Engraver",
"elg": "Electrician",
"elt": "Electrotyper",
"eng": "Engineer",
"enj": "Enacting jurisdiction",
"etr": "Etcher",
"evp": "Event place",
"exp": "Expert",
"fac": "Facsimilist",
"fds": "Film distributor",
"fld": "Field director",
"flm": "Film editor",
"fmd": "Film director",
"fmk": "Filmmaker",
"fmo": "Former owner",
"fmp": "Film producer",
"fnd": "Funder",
"fpy": "First party",
"frg": "Forger",
"gis": "Geographic information specialist",
"grt": "Graphic technician",
"his": "Host institution",
"hnr": "Honoree",
"hst": "Host",
"ill": "Illustrator",
"ilu": "Illuminator",
"ins": "Inscriber",
"inv": "Inventor",
"isb": "Issuing body",
"itr": "Instrumentalist",
"ive": "Interviewee",
"ivr": "Interviewer",
"jud": "Judge",
"jug": "Jurisdiction governed",
"lbr": "Laboratory",
"lbt": "Librettist",
"ldr": "Laboratory director",
"led": "Lead",
"lee": "Libelee-appellee",
"lel": "Libelee",
"len": "Lender",
"let": "Libelee-appellant",
"lgd": "Lighting designer",
"lie": "Libelant-appellee",
"lil": "Libelant",
"lit": "Libelant-appellant",
"lsa": "Landscape architect",
"lse": "Licensee",
"lso": "Licensor",
"ltg": "Lithographer",
"lyr": "Lyricist",
"mcp": "Music copyist",
"mdc": "Metadata contact",
"med": "Medium",
"mfp": "Manufacture place",
"mfr": "Manufacturer",
"mod": "Moderator",
"mon": "Monitor",
"mrb": "Marbler",
"mrk": "Markup editor",
"msd": "Musical director",
"mte": "Metal-engraver",
"mtk": "Minute taker",
"mus": "Musician",
"nrt": "Narrator",
"opn": "Opponent",
"org": "Originatorv",
"orm": "Organizer",
"osp": "Onscreen presenter",
"oth": "Other",
"own": "Owner",
"pad": "Place of address",
"pan": "Panelist",
"pat": "Patron",
"pbd": "Publishing director",
"pbl": "Publisher",
"pdr": "Project director",
"pfr": "Proofreader",
"pht": "Photographer",
"plt": "Platemaker",
"pma": "Permitting agency",
"pmn": "Production manager",
"pop": "Printer of plates",
"ppm": "Papermaker",
"ppt": "Puppeteer",
"pra": "Praeses",
"prc": "Process contact",
"prd": "Production personnel",
"pre": "Presenter",
"prf": "Performer",
"prg": "Programmer",
"prm": "Printmaker",
"prn": "Production company",
"pro": "Producer",
"prp": "Production place",
"prs": "Production designer",
"prt": "Printer",
"prv": "Provider",
"pta": "Patent applicant",
"pte": "Plaintiff-appellee",
"ptf": "Plaintiff",
"pth": "Patent holder",
"ptt": "Plaintiff-appellant",
"pup": "Publication place",
"rbr": "Rubricator",
"rcd": "Recordist",
"rce": "Recording engineer",
"rcp": "Addressee",
"rdd": "Radio director",
"red": "Redaktor",
"ren": "Renderer",
"res": "Researcher",
"rev": "Reviewer",
"rpc": "Radio producer",
"rps": "Repository",
"rpt": "Reporter",
"rpy": "Responsible party",
"rse": "Respondent-appellee",
"rsg": "Restager",
"rsp": "Respondent",
"rsr": "Restorationist",
"rst": "Respondent-appellant",
"rth": "Research team head",
"rtm": "Research team member",
"sad": "Scientific advisor",
"sce": "Scenarist",
"scl": "Sculptor",
"scr": "Scribe",
"sds": "Sound designer",
"sec": "Secretary",
"sgd": "Stage director",
"sgn": "Signer",
"sht": "Supporting host",
"sll": "Seller",
"sng": "Singer",
"spk": "Speaker",
"spn": "Sponsor",
"spy": "Second party",
"srv": "Surveyor",
"std": "Set designer",
"stg": "Setting",
"stl": "Storyteller",
"stm": "Stage manager",
"stn": "Standards body",
"str": "Stereotyper",
"tcd": "Technical director",
"tch": "Teacher",
"ths": "Thesis advisor",
"tld": "Television director",
"tlp": "Television producer",
"trc": "Transcriber",
"trl": "Translator",
"tyd": "Type designer",
"tyg": "Typographer",
"uvp": "University place",
"vac": "Voice actor",
"vdg": "Videographer",
"voc": "Vocalist",
"wac": "Writer of added commentary",
"wal": "Writer of added lyrics",
"wam": "Writer of accompanying material",
"wat": "Writer of added text",
"wdc": "Woodcutter",
"wde": "Wood engraver",
"win": "Writer of introduction",
"wit": "Witness",
"wpr": "Writer of preface",
"wst": "Writer of supplementary textual content"}
