lookup_sameAs = {
    "(DE-588)":{
        "@id": "https://d-nb.info/",
        "publisher": {"preferredName": "Deutsche Nationalbibliothek",
                      "@id": "https://ld.zdb-services.de/resource/organisations/DE-101",
                      "abbr": "DNB"}
        },
    "(DE-627)": {
        "@id": "https://opac.k10plus.de/DB=2.299/PPNSET?PPN=",
        "publisher": {"preferredName": "K10Plus",
                      "@id": "https://ld.zdb-services.de/resource/organisations/DE-627",
                      "abbr": "KXP"}
        },
    "(DE-576)": {
        "@id": "https://swb.bsz-bw.de/DB=2.1/PPNSET?PPN=",
        "publisher": {
            "@id": "https://ld.zdb-services.de/resource/organisations/DE-576",
            "preferredName": "Bibliotheksservice-Zentrum Baden-Württemberg (BSZ)",
            "abbr": "BSZ"
        }
    },
    "(DE-600)": {
        "@id": "https://ld.zdb-services.de/resource/",
        "publisher": {
            "@id": "https://ld.zdb-services.de/resource/organisations/DE-600",
            "preferredName": "Zeitschriftendatenbank (ZDB)",
            "abbr": "ZDB"
        }
    },
    "(DE-601)": {
        "@id": "http://gso.gbv.de/PPN?PPN="
            },
    "(DE-633)": {
        "@id": "https://opac.rism.info/id/rismid/",
        "publisher": {
            "@id": "https://ld.zdb-services.de/resource/organisations/DE-633",
            "preferredName": "Répertoire International des Sources Musicales",
            "abbr": "RISM"
        }
    }
}


map_entities = {
    "p": "persons",  # Personen, individualisiert
    "n": "persons",  # Personen, namen, nicht individualisiert
    "s": "topics",  # Schlagwörter/Berufe
    "b": "organizations",  # Organisationen
    "g": "geo",  # Geographika
    "u": "works",  # Werktiteldaten
    "f": "events"
}

map_types = {
    "p": "Person",  # Personen, individualisiert
    "n": "Person",  # Personen, namen, nicht individualisiert
    "s": "Thing",  # Schlagwörter/Berufe
    "b": "Organization",  # Organisationen
    "g": "Place",  # Geographika
    "u": "CreativeWork",  # Werktiteldaten
    "f": "Event"
}

marc2relation = {
    "VD-16 Mitverf": "contributor",
    "v:Mitverf": "contributor",
    "v:Co-Autor": "contributor",
    "v:Doktorvater": "contributor",
    "v:Illustrator": "contributor",
    "v:Übersetzer": "contributor",
    "v:Biograf": "contributor",
    "v:Förderer": "contributor",
    "v:Berater": "contributor",
    "v:hrsg": "contributor",
    "v:Mitautor": "contributor",
    "v:Partner": "contributor",
    
    "v:Tocher": "children",            #several typos in SWB dataset
    "tochter": "children",
    "Z:Tochter":"children",
    "Sohn": "children",
    "v:Nachkomme": "children",
    "v:zweites Kind": "children",
    
    "v:Erste Ehefrau":"spouse",
    "v:Zweite Ehefrau":"spouse",
    "v:Gattin": "spouse",
    "v:Gatte": "spouse",
    "v:Gemahl": "spouse",
    "Ehe": "spouse",
    "Frau": "spouse",
    "Mann": "spouse",
    
    "v:Jüngster Bruder": "sibling",
    "Bruder": "sibling",
    "v:Zwilling": "sibling",
    "Schwester": "sibling",
    "v:Halbschwester": "sibling",
    "v:Halbbruder": "sibling",
    "Vater": "parent",
    "Z:Vater":"parent",
    "v:Stiefvater": "parent",
    "Mutter": "parent",
    
    "Nachfolger": "follows",
    "Vorgänger": "follows",
    
    "v:Vorfahr": "relatedTo",
        
    "v:Schüler": "relatedTo",        
    "Lehrer": "relatedTo",        
    "v:frühere Ehefrau": "relatedTo",
    "v:Schwager": "relatedTo",        
    "v:Ur": "relatedTo",          
    "v:Muse": "relatedTo",
    "v:Nachfahre": "relatedTo",         
    "v:Groß": "relatedTo",    
    "v:Langjähriger Geliebter": "relatedTo",    
    "v:Lebensgefährt": "relatedTo",    
    "v:Nichte": "relatedTo",
    "v:Stiefnichte": "relatedTo",
    "v:Neffe": "relatedTo",
    "v:Onkel": "relatedTo",
    "v:Tante": "relatedTo",
    "v:Verlobt": "relatedTo",
    "v:Vorfahren": "relatedTo",
    "v:Vetter": "relatedTo",
    "v:Tauf": "relatedTo",
    "v:Pate": "relatedTo",
    "v:Schwägerin": "relatedTo",
    "v:Schwiegervater": "relatedTo",
    "v:Schwiegermutter": "relatedTo",
    "v:Schwiegertochter": "relatedTo",
    "v:Schwiegersohn": "relatedTo",
    "v:Enkel": "relatedTo",
    "v:Mätresse": "relatedTo",
    "Freund": "knows",
    "v:Großvater": "relatedTo",
    "v:Cousin": "relatedTo",
    "v:Lebenspartner": "relatedTo",
    "v:Berater und Freund": "relatedTo",
    "v:Geliebte": "relatedTo",
    "v:Modell und Lebensgefährtin":"relatedTo",
    "v:Liebesbeziehung":"relatedTo",
    
    "v:publizistische Zusammenarbeit und gemeinsame öffentliche Auftritte": "colleague",
    "v:Sekretär": "colleague", 
    "v:Privatsekretär": "colleague", 
    "v:Kolleg": "colleague", 
    "v:Mitarbeiter": "colleague", 
    "v:Kommilitone": "colleague", 
    "v:Zusammenarbeit mit": "colleague", 
    "v:gemeinsames Atelier": "colleague", 
    "v:Geschäftspartner": "colleague" , 
    "v:musik. Partnerin": "colleague" ,
    "v:Künstler. Partner": "colleague" ,  
    "assistent": "colleague",
    
    #see also http://www.dnb.de/SharedDocs/Downloads/DE/DNB/standardisierung/inhaltserschliessung/gndCodes.pdf?__blob=publicationFile
    "adel":"honorificPrefix",
    "adre":"recipent",
    "adue":"parentOrganization",
    "affi":"affiliation",
    #"akad":"honorificPrefix",
    "akti":"hasProfession",
    "bezf":"relatedTo",
    "bezb":"colleague",
    "beza":"knows",
    "bete": "contributor",
    "rela":"knows",
    "affi":"knows",
    "aut1":"author",
}


rolemapping={
"abr":"KürzendeR",
"acp":"HerstellerIn von Nachbildungen",
"act":"SchauspielerIn",
"adi":"Art Director",
"adp":"BearbeiterIn",
"aft":"VerfasserIn eines Nachworts",
"anl":"AnalytikerIn",
"anm":"TrickfilmzeichnerIn",
"ann":"KommentatorIn",
"ant":"BibliographischeR VorgängerIn",
"ape":"BerufungsbeklagteR/RevisionsbeklagteR",
"apl":"BerufungsklägerIn/RevisionsklägerIn",
"app":"AntragstellerIn",
"aqt":"AutorIn von Zitaten oder Textabschnitten",
"arc":"ArchitektIn",
"ard":"künstlerische Leitung",
"arr":"ArrangeurIn",
"art":"KünstlerIn",
"asg":"RechtsnachfolgerIn",
"asn":"zugehöriger Name",
"ato":"AutographIn",
"att":"zugehöriger Name",
"auc":"AuktionatorIn",
"aud":"AutorIn des Dialogs",
"aui":"VerfasserIn eines Geleitwortes",
"aus":"DrehbuchautorIn",
"aut":"VerfasserIn",
"bdd":"BindungsgestalterIn",
"bjd":"EinbandgestalterIn",
"bkd":"BuchgestalterIn",
"bkp":"BuchherstellerIn",
"blw":"AutorIn des Klappentextes",
"bnd":"BuchbinderIn",
"bpd":"GestalterIn des Exlibris",
"brd":"Sender",
"brl":"BrailleschriftprägerIn",
"bsl":"BuchhändlerIn",
"cas":"FormgießerIn",
"ccp":"konzeptionelle Leitung",
"chr":"ChoreografIn",
"clb":"MitarbeiterIn",
"cli":"KlientIn, AuftraggeberIn",
"cll":"KalligrafIn",
"clr":"KoloristIn",
"clt":"LichtdruckerIn",
"cmm":"KommentatorIn",
"cmp":"KomponistIn",
"cmt":"SchriftsetzerIn",
"cnd":"DirigentIn",
"cng":"Kameramann/frau",
"cns":"ZensorIn",
"coe":"BerufungsbeklagteR im streitigen Verfahren",
"col":"SammlerIn",
"com":"ZusammenstellendeR",
"con":"KonservatorIn",
"cor":"SammlungskuratorIn",
"cos":"AnfechtendeR, bestreitende Partei",
"cot":"BerufungsklägerIn im streitigen Verfahren",
"cou":"zuständiges Gericht",
"cov":"UmschlaggestalterIn",
"cpc":"BeansprucherIn des Urheberrechts",
"cpe":"BeschwerdeführerIn-BerufungsbeklagteR",
"cph":"InhaberIn des Urheberrechts",
"cpl":"BeschwerdeführerIn/KlägerIn",
"cpt":"KlägerIn/BerufungsklägerIn",
"cre":"GeistigeR SchöpferIn",
"crp":"KorrespondentIn",
"crr":"KorrektorIn",
"crt":"GerichtsstenografIn",
"csl":"BeraterIn",
"csp":"ProjektberaterIn",
"cst":"KostümbildnerIn",
"ctb":"MitwirkendeR",
"cte":"AnfechtungsgegnerIn-BerufungsbeklagteR",
"ctg":"KartografIn",
"ctr":"VertragspartnerIn",
"cts":"AnfechtungsgegnerIn",
"ctt":"AnfechtungsgegnerIn-BerufungsklägerIn",
"cur":"KuratorIn",
"cwt":"KommentatorIn",
"dbp":"Erscheinungsort",
"dfd":"AngeklagteR/BeklagteR",
"dfe":"AngeklagteR/BeklagteR-BerufungsbeklagteR",
"dft":"AngeklagteR/BeklagteR-BerufungsklägerIn",
"dgg":"Grad-verleihende Institution",
"dgs":"AkademischeR BetreuerIn",
"dir":"Dirigent",
"dis":"PromovierendeR",
"dln":"VorzeichnerIn",
"dnc":"TänzerIn",
"dnr":"GeldgeberIn",
"dpc":"AbgebildeteR",
"dpt":"AnlegerIn",
"drm":"TechnischeR ZeichnerIn",
"drt":"RegisseurIn",
"dsr":"DesignerIn",
"dst":"Vertrieb",
"dtc":"BereitstellerIn von Daten",
"dte":"WidmungsempfängerIn",
"dtm":"DatenmanagerIn",
"dto":"WidmendeR",
"dub":"angeblicheR AutorIn",
"edc":"BearbeiterIn der Zusammenstellung",
"edm":"CutterIn",
"edt":"HerausgeberIn",
"egr":"StecherIn",
"elg":"ElektrikerIn",
"elt":"GalvanisiererIn",
"eng":"IngenieurIn",
"enj":"Normerlassende Gebietskörperschaft",
"etr":"RadiererIn",
"evp":"Veranstaltungsort",
"exp":"ExperteIn",
"fac":"FacsimilistIn",
"fds":"Filmvertrieb",
"fld":"BereichsleiterIn",
"flm":"BearbeiterIn des Films",
"fmd":"FilmregisseurIn",
"fmk":"FilmemacherIn",
"fmo":"frühereR BesitzerIn",
"fmp":"FilmproduzentIn",
"fnd":"GründerIn",
"fpy":"Erste Partei",
"frg":"FälscherIn",
"gis":"GeographIn",
"grt":"GraphischeR TechnikerIn",
"hg":"Herausgeber",
"his":"Gastgebende Institution",
"hnr":"GefeierteR",
"hst":"GastgeberIn",
"Ill":"Illustrator",
"ill":"IllustratorIn",
"ilu":"Illuminator, BuchmalerIn",
"ins":"InserierendeR",
"inv":"ErfinderIn",
"isb":"Herausgebendes Organ",
"itr":"InstrumentalmusikerIn",
"ive":"InterviewteR",
"ivr":"InterviewerIn",
"jud":"RichterIn",
"jug":"zuständige Gerichtsbarkeit",
"kad":"Kadenzverfasser",
"lbr":"Labor",
"lbt":"LibrettistIn",
"ldr":"Laborleitung",
"led":"Führung",
"lee":"Libelee-appellee",
"lel":"BeklagteR im Seerecht/Kirchenrecht",
"len":"LeihgeberIn",
"let":"Libelee-appellant",
"lgd":"LichtgestalterIn",
"lie":"Libelant-appellee",
"lil":"KlägerIn im Seerecht/Kirchenrecht",
"lit":"Libelant-appellant",
"lsa":"LandschaftsarchitektIn",
"lse":"LizenznehmerIn",
"lso":"LizenzgeberIn",
"ltg":"LithographIn",
"lyr":"TextdichterIn",
"mcp":"ArrangeurIn, Notenleser/-schreiberIn",
"mdc":"Metadatenkontakt",
"med":"Medium",
"mfp":"Herstellungsort",
"mfr":"HerstellerIn",
"mod":"ModeratorIn",
"mon":"BeobachterIn",
"mrb":"MarmorarbeiterIn, MarmoriererIn",
"mrk":"Markup-EditorIn",
"msd":"MusikalischeR LeiterIn",
"mte":"Metall-GraveurIn",
"mtk":"ProtokollantIn",
"mus":"MusikerIn",
"nrt":"ErzählerIn",
"opn":"GegnerIn",
"org":"UrheberIn",
"orm":"VeranstalterIn",
"osp":"On-screen PräsentatorIn",
"oth":"BerichterstatterIn",
"own":"BesitzerIn",
"pan":"DiskussionsteilnehmerIn",
"pat":"SchirmherrIn",
"pbd":"Verlagsleitung",
"pbl":"Verlag",
"pdr":"Projektleitung",
"pfr":"Korrektur",
"pht":"FotografIn",
"plt":"DruckformherstellerIn",
"pma":"Genehmigungsstelle",
"pmn":"Produktionsleitung",
"pop":"PlattendruckerIn",
"ppm":"PapiermacherIn",
"ppt":"PuppenspielerIn",
"pra":"Praeses",
"prc":"Prozesskontakt",
"prd":"Produktionspersonal",
"pre":"PräsentatorIn",
"prf":"AusführendeR",
"prg":"ProgrammiererIn",
"prm":"DruckgrafikerIn",
"prn":"Produktionsfirma",
"pro":"ProduzentIn",
"prp":"Produktionsort",
"prs":"SzenenbildnerIn",
"prt":"DruckerIn",
"prv":"AnbieterIn",
"pta":"PatentanwärterIn",
"pte":"KlägerIn-BerufungsbeklagteR",
"ptf":"ZivilklägerIn",
"pth":"PatentinhaberIn",
"ptt":"KlägerIn-BerufungsklägerIn",
"pup":"Veröffentlichungsort",
"rbr":"RubrikatorIn",
"rcd":"TonmeisterIn",
"rce":"ToningenieurIn",
"rcp":"AdressatIn",
"rdd":"HörfunkregisseurIn",
"Red":"Redakteur",
"red":"RedakteurIn",
"ren":"RendererIn (Bildverarbeitung)",
"res":"ForscherIn",
"rev":"RezensentIn, GutachterIn",
"rpc":"HörfunkproduzentIn",
"rps":"Aufbewahrungsort, TreuhänderIn",
"rpt":"ReporterIn",
"rpy":"Verantwortliche Partei",
"rse":"AntragsgegnerIn-BerufungsbeklagteR",
"rsg":"RegisseurIn der Wiederaufführung",
"rsp":"RespondentIn",
"rsr":"RestauratorIn",
"rst":"AntragsgegnerIn-BerufungsklägerIn",
"rth":"Leitung des Forschungsteams",
"rtm":"Mitglied des Forschungsteams",
"sad":"WissenschaftlicheR BeraterIn",
"sce":"DrehbuchautorIn",
"scl":"BildhauerIn",
"scr":"SchreiberIn",
"sds":"Tongestalter",
"sec":"SekretärIn",
"sgd":"BühnenregisseurIn",
"sgn":"UnterzeichnerIn",
"sht":"Unterstützender Veranstalter",
"sll":"VerkäuferIn",
"sng":"SängerIn",
"spk":"RednerIn",
"spn":"SponsorIn",
"spy":"Zweite Partei",
"srv":"LandvermesserIn",
"std":"BühnenbildnerIn",
"stg":"Kulisse",
"stl":"GeschichtenerzählerIn",
"stm":"InszenatorIn",
"stn":"Normungsorganisation",
"str":"StereotypeurIn",
"tcd":"Technische Leitung",
"tch":"LehrerIn",
"ths":"BetreuerIn (Doktorarbeit)",
"tld":"FernsehregisseurIn",
"tlp":"FernsehproduzentIn",
"trc":"TranskribiererIn",
"trl":"ÜbersetzerIn",
"tyd":"Schrift-DesignerIn",
"tyg":"SchriftsetzerIn",
"uvp":"Hochschulort",
"vac":"SynchronsprecherIn",
"vdg":"BildregisseurIn",
"voc":"VokalistIn",
"wac":"KommentarverfasserIn",
"wal":"VerfasserIn von zusätzlichen Lyrics",
"wam":"AutorIn des Begleitmaterials",
"wat":"VerfasserIn von Zusatztexten",
"wdc":"HolzschneiderIn",
"wde":"HolzschnitzerIn",
"win":"VerfasserIn einer Einleitung",
"wit":"ZeugeIn",
"wpr":"VerfasserIn eines Vorworts",
"wst":"VerfasserIn von ergänzendem Text"
}

lookup_ssg_fid = {"0": "SSG Allgemeine und vergleichende Religionswissenschaft",
"1": "SSG Theologie",
"2": "SSG Rechtswissenschaften",
"2,1": "SSG Kriminologie und Kriminalistik",
"3,1": "SSG Volkswirtschaft und Weltwirtschaft",
"3,2": "SSG Betriebswirtschaft",
"3,4": "SSG Sozialwissenschaften",
"3,5": "SSG Kommunikations- und Medienwissenschaft, Publizistik",
"3,6": "SSG Politik, Friedensforschung",
"3,61": "SSG Parteien und Gewerkschaften aus Europa und Nordamerika (nicht-konventionelle Literatur)",
"3,7": "SSG Verwaltungswissenschaften",
"3,8": "SSG Kommunalwissenschaften (nur deutschsprachigen Bereich)",
"4": "SSG Medizin",
"5,1": "SSG Philosophie",
"5,2": "SSG Psychologie",
"5,21": "SSG Grenzgebiete der Psychologie, Parapsychologie",
"5,3": "SSG Bildungsforschung",
"5,31": "SSG Deutschsprachige Bildungsgeschichte (bis 1989/1990)",
"6,11": "SSG Vor- und Frühgeschichte",
"6,12": "SSG Klassische Altertumswissenschaft, inclusive alte Geschichte, Mittel- und Neulateinische Philologie",
"6,14": "SSG Klassische Archäologie",
"6,15": "SSG Byzanz",
"6,16": "SSG Neuzeitliches Griechenland",
"6,21": "SSG Ägyptologie",
"6,22": "SSG Alter Orient",
"6,23": "SSG Vorderer Orient inclusive Nordafrika",
"6,231": "SSG Nicht-konventionelles Material aus dem Vorderen Orient",
"6,24": "SSG Südasien",
"6,25": "SSG Ost- und Südostasien",
"6,251": "SSG Nicht-konventionelles Material aus Ost- und Südostasien",
"6,26": "SSG Altaische und paläoasiatische Sprachen und Literaturen",
"6,31": "SSG Afrika südlich der Sahara",
"6,311": "SSG Nicht-konventionelle Materialien aus Afrika",
"6,32": "SSG Ozeanien",
"6,33": "SSG Indianer- und Eskimosprachen und -kulturen",
"7,11": "SSG Allgemeine und vergleichende Sprachwissenschaft, Allgemeine Linguistik",
"7,12": "SSG Allgemeine und vergleichende Literaturwissenschaft",
"7.20": "SSG Germanistik, Deutsche Sprache und Literatur",
"7,22": "SSG Skandinavien",
"7,23": "SSG Benelux",
"7,24": "SSG Anglistik",
"7,25": "SSG Großbritannien und Irland",
"7,26": "SSG Nordamerika",
"7,261": "SSG Noramerikanische Zeitungen",
"7,27": "SSG Keltologie",
"7,29": "SSG Australien, Neuseeland",
"7,30": "SSG Romanistik Allgemeine",
"7,31": "SSG Französische Sprache und Literatur",
"7,32": "SSG Italienische Sprache und Literatur",
"7,34": "SSG Spanien, Portugal",
"7,36": "SSG Ibero-Amerika",
"7,38": "SSG Rumänische Sprache und Literatur",
"7,39": "SSG Slawistik",
"7,41": "SSG Ost-, Ostmittel- und Südosteueropa",
"7,43": "SSG Albanische Sprache und Literatur",
"7,44": "SSG Baltische Länder",
"7,50": "SSG Finno-Ugristik",
"7,51": "SSG Finnland",
"7,52": "SSG Ungarn",
"7,53": "SSG Estnische Sprache  und Literatur",
"7,6": "SSG  Israel",
"7,7": "SSG Judentum",
"8": "SSG Geschichte",
"8,1": "SSG Geschichte Deutschlands, Österreichs und der Schweiz",
"8,2": "SSG Geschichte Frankreichs und Italiens",
"9,10": "SSG Allgemeine Kunstwissenschaft, Mittlere und neuere Kunstgeschichte bis 1945",
"9,11": "SSG Zeitgenössische Kunst ab 1945",
"9,2": "SSG Musikwissenschaft",
"9,3": "SSG Theater- und Filmkunst",
"10": "SSG Volks- und Völkerkunde",
"11": "SSG Allgemeine Naturwissenschaften",
"12": "SSG Biologie",
"13": "SSG Geologie, Mineralogie, Petrologie, Bodenkunde",
"13,1": "SSG Regionale Geologie",
"14": "SSG Geographie",
"14,1": "SSG Veröffentlichungen zur Karthographie",
"15": "SSG Chemie",
"15,3": "SSG Pharmazie",
"16": "SSG Physik",
"16,12": "SSG Astronomie, Astrophysik, Weltraumforschung",
"16,13": "SSG Geophysik",
"16,14": "SSG Metereologie",
"16,15": "SSG Physikalische Ozeanographie",
"17,1": "SSG Reine Mathematik",
"17,2": "SSG Angewandte Mathematik",
"17,3": "SSG Geodäsie und Vermessungswesen",
"18": "SSG Informatik, Datenverarbeitung",
"19": "SSG Ingenieurwissenshaft, Technik",
"19,1": "SSG Bergbau, Markscheidekunde, Hüttenwesen",
"19,2": "SSG Technikgeschichte",
"20": "SSG Architektur, Städtebau, Landesplanung, Raumordnung",
"20,3": "SSG Nichtkonventionelle Materialien zu Städtebau, Landesplanung, Raumordnung aus dem deutschsprachigen Raum",
"21": "SSG Agrarwissenschaften",
"21,3": "SSG Küsten- und Hochseefischerei",
"22": "SSG Veterinärmedizin, Allgemeine Parasitologie",
"23": "SSG Forstwissenschaft",
"24,1": "SSG Informations-, Buch- und  Bibliothekswesen",
"24,2": "SSG Hochschulwesen, Organisation der Wissenschaften und ihrer Einrichtungen",
"25": "SSG Universale wissenschaftliche Zeitschriften",
"26": "SSG Ausländische Zeitungen",
"27": "SSG Parlamentsschriften",
"28,1": "SSG Topographisch Karten",
"28,2": "SSG Thematische Karten",
"28,3": "SSG Seekarten",
"28,4": "SSG Meteorologische und klimatologische Karten",
"30": "SSG Schulbücher",
"31": "SSG Sportwissenschaft",
"AAC": "FID Anglo-American Culture (FID Anglistik / Großbritannien- und Irlandstudien; FID Amerikastudien; FID Kanadastudien; FID Australien- und Neuseelandstudien)",
"ALT": "FID Altertumswissenschaften - Propylaeum",
"ALT-KA": "FID Altertumswissenschaften - Propylaeum",
"ALT-AY": "FID Altertumswissenschaften - Propylaeum",
"AFRIKA": "FID Afrikastudien",
"ASIEN": "FID Asien - CrossAsia",
"AVL": "FID Komparatistik - Allgemeine und Vergleichende Literaturwissenschaft",
"BBI": "FID Buch-, Bibliotheks- und Informationswissenschaft",
"BENELUX": "FID Benelux / Low Countries Studies",
"BIFO": "FID Erziehungswissenschaft und Bildungsforschung",
"BIFO-HF": "FID Erziehungswissenschaft und Bildungsforschung",
"BIODIV": "FID Bio­diversitäts­forschung",
"GEO": "FID Geowissenschaften der festen Erde",
"GER": "FID Germanistik",
"FINNUG": "FID Finnisch-ugrische / uralische Sprachen, Literaturen und Kulturen",
"HIST": "FID Geschichtswissenschaft",
"INTRECHT": "FID internationale und interdisziplinäre Rechtsforschung",
"JUDAICA": "FID Jüdische Studien",
"KARTEN": "FID Kartographie und Geobasisdaten",
"KRIM": "FID Kriminologie",
"KUNST": "FID Kunst, Fotografie, Design - arthistoricum.net",
"Kunst": "FID Kunst, Fotografie, Design - arthistoricum.net",
"LATAM": "FID Lateinamerika, Karibik und Latino Studies",
"LING": "FID Linguistik",
"MATHE": "FID Mathematik",
"MEDIEN": "FID Medien-, Kommunikations- und Filmwissenschaften",
"MONTAN": "FID Montan (Bergbau und Hüttenwesen)",
"MOVE": "FID Mobilitäts- und Verkehrsforschung",
"MUS": "FID Musikwissenschaft",
"NAHOST": "FID Nahost-, Nordafrika- und Islamstudien",
"NORD": "FID Nordeuropa",
"OST": "FID Ost-, Ostmittel- und Südosteuropa",
"PHARM": "FID Pharmazie",
"PHILOS": "FID Philosophie",
"POL": "FID Politik­wissenschaft",
"REWI": "FID Religionswissenschaft",
"ROM": "FID Romanistik",
"SKA": "FID Sozial- und Kulturanthropologie",
"SLAW": "FID Slawistik",
"SOZIO": "FID Soziologie",
"THEATER": "FID Darstellende Kunst",
"THEO": "FID Theologie",
"ZENTRALASIEN": "FID Zentralasien - Autochthone Kulturen und Sprachen"
}

lookup_coll = {
"AUGU": "Augustinus-Literaturdatenbank Würzburg",
"BA": "Bibliotheken der Aufklärungszeit",
"BGTS": "Bibliographie Geschichte der Technik (Vergabe durch die SLUB Dresden)",
"BIDL": "Mikrofiche-Ausgabe der \"Bibliothek der Deutschen Literatur\"",
"BIIN": "Bibelwissenschaftliche Literaturdokumentation Innsbruck (IxTheo)",
"BIST": "Mikrofiche-Ausgabe der \"Bibliothek Stein\"",
"CeDi": "Centralasia Digital",
"CICO": "Mikrofiche-Ausgabe der \"Cicognara Library\"",
"DAKR": "Datenbank Kanonisches Recht Münster",
"DTH5": "Aufsätze und Rezensionen aus dem Digitalisierungsprojekt theologischer Zeitschriften DigiTheo_5",
"EDCO": "Mikrofiche-Ausgabe der \"Edition Corvey\"",
"FOOD": "Food studies",
"GIRA": "Literaturdokumentation zur Mimetischen Theorie von René Girard Innsbruck",
"HistGuide": "History Guide: Fachkatalog digitaler Ressourcen für die Geschichtswissenschaft",
"INKA": "Daten übernommen aus dem Inkunabelkatalog deutscher Bibliotheken (INKA)",
"KALD": "Kanonistische Literaturdokumentation Innsbruck (IxTheo)",
"KLOK": "Kulturrat Oldenburg Karten",
"krex": "Manueller Eintrag bei maschinell selektierten Datensätzen für KrimDok, die keinen kriminologischen Bezug haben",
"leos": "In LEO-BW verwendet",
"MIKA": "Missionsbibliothek und katholische Dokumentationsstelle des MWI Aachen (IxTheo)",
"MENAdoc": "Fachinformationsdienst Nahost-, Nordafrika- und Islamstudien der Universitäts- und Landesbibliothek Sachsen-Anhalt (Halle)",
"mkri": "Fachinformationsdienst Kriminologie",
"mteo": "Theologische und religionswiss. Titel, maschinell gekennzeichnet",
"OERR": "Open educational resources Repositorium",
"PAHA": "Palatina-Handschrift",
"PALA": "Mikrofiche-Ausgabe der \"Bibliotheca Palatina\"",
"PZ": "Pommersche Zeitungen/Zeitschriften",
"redo": "Religionswissenschaft/Dokumentationsstelle",
"SAVE": "Sicherung des audiovisuellen Erbes in Sachsen",
"SAXB": "Titel aus der Sächsischen Bibliographie (Vergabe durch die SLUB Dresden)",
"SP": "Sammlung Perthes",
"VDLN": "Verteilte digitale Landesbibliothek Niedersachsen",
"WABU": "Mikrofiche-Ausgabe der \"Edition St. Walburg\" (Frauenklosterbibliothek St. Walburg)",
"WLMMA": "Wolfgang Laade Music of Man Archive",
}
