classifications = { "ssgn": {"@type": "CategoryCodeSet",
                            "name": "Sondersammelgebiets-Nummer",
                            "alternateName": ["SSG", "SSGN"],
                            "sameAs": "https://www.wikidata.org/wiki/Q71786666",
                            "CategoryCodes": [{"@type": "CategoryCode",
                                               "codeValue": None}]},
                    "sdnb": {"@type": "CategoryCodeSet",
                            "name": "Sachgruppen der DNB bis 2003",
                            "alternateName": ["SDNB bis 2003", "Systematik der Deutschen Nationalbibliografie bis 2003", "DNB-Sachgruppen bis 2003", "Sachgruppen der Deutschen Nationalbibliografie bis 2003"],
                            "sameAs": "https://www.wikidata.org/wiki/Q113660734",
                            "CategoryCodes": [{"@type": "CategoryCode",
                                               "codeValue": None}]},
                    "fid": {"@type": "CategoryCodeSet",
                            "name":  "Kennzeichen der DFG geförderten Fachinformationsdienste für die Wissenschaft",
                            "alternateName": ["FID", "FID Kennzeichen"],
                            "sameAs": "http://wikis.sub.uni-hamburg.de/webis/index.php/Webis_-_Sammelschwerpunkte_an_deutschen_Bibliotheken",
                            "CategoryCodes": [{"@type": "CategoryCode",
                                               "codeValue": None}]},
                    "bkl": {"@type": "CategoryCodeSet",
                            "@id": "http://uri.gbv.de/terminology/bk/",
                            "name":  "Basisklassifikation",
                            "alternateName": ["BKL", "BK"],
                            "sameAs": "https://www.wikidata.org/wiki/Q29938469",
                            "CategoryCodes": [{"@type": "CategoryCode",
                                               "@id": "http://uri.gbv.de/terminology/bk/",
                                               "codeValue": None}]},
                    "rvk": {"@type": "CategoryCodeSet",
                            "@id": "https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online",
                            "name":  "Regensburger Verbundklassifikation",
                            "alternateName": ["RVK", "Regensburger Systematik", "RVKO", "Regensburg RVK", "Regensburg Classification" ],
                            "sameAs": "http://www.wikidata.org/wiki/Q2137453",
                            "CategoryCodes": [{"@type": "CategoryCode",
                                                    "@id": "https://rvk.uni-regensburg.de/regensburger-verbundklassifikation-online#notation/",
                                                    "codeValue": None}]},
                    "082.0_": {"@type": "CategoryCodeSet",
                           "name": "Dewey Decimal Classification",
                           "alternateName": "DDC",
                           "sameAs": "http://www.wikidata.org/wiki/Q48460",
                           "CategoryCodes": [{"@type": "CategoryCode",
                                              "codeValue": None}]},
                    "082.04": {"@type": "CategoryCodeSet",
                           "name": "DDC-Sachgruppen der DNB ab 2004",
                           "alternateName": ["Sachgruppen der DNB ab 2004", "SDNB ab 2004", "Systematik der Deutschen Nationalbibliografie ab 2004", "DNB-Sachgruppen ab 2004", "Sachgruppen der Deutschen Nationalbibliografie ab 2004"],
                           "sameAs": "https://www.wikidata.org/wiki/Q67011877",
                           "CategoryCodes": [{"@type": "CategoryCode",
                                              "codeValue": None}]},
                    "050._0": {"@type": "CategoryCodeSet",
                         "@id": "https://id.loc.gov/authorities/classification",
                         "name": "Library of Congress Classification",
                         "alternateName": "LCC",
                         "sameAs": "https://wikidata.org/wiki/Q621080",
                         "CategoryCodes": [{"@type": "CategoryCode",
                                 "@id": "https://id.loc.gov/authorities/classification/",
                                 "codeValue": None}]}
                         }
