lookup_ssg_fid = {"0": "SSG Allgemeine und vergleichende Religionswissenschaft",
"1": "SSG Theologie",
"2": "SSG Rechtswissenschaften",
"2,1": "SSG Kriminologie und Kriminalistik",
"3,1": "SSG Volkswirtschaft und Weltwirtschaft",
"3,2": "SSG Betriebswirtschaft",
"3,4": "SSG Sozialwissenschaften",
"3,5": "SSG Kommunikations- und Medienwissenschaft, Publizistik",
"3,6": "SSG Politik, Friedensforschung",
"3,61": "SSG Parteien und Gewerkschaften aus Europa und Nordamerika (nicht-konventionelle Literatur)",
"3,7": "SSG Verwaltungswissenschaften",
"3,8": "SSG Kommunalwissenschaften (nur deutschsprachigen Bereich)",
"4": "SSG Medizin",
"5,1": "SSG Philosophie",
"5,2": "SSG Psychologie",
"5,21": "SSG Grenzgebiete der Psychologie, Parapsychologie",
"5,3": "SSG Bildungsforschung",
"5,31": "SSG Deutschsprachige Bildungsgeschichte (bis 1989/1990)",
"6,11": "SSG Vor- und Frühgeschichte",
"6,12": "SSG Klassische Altertumswissenschaft, inclusive alte Geschichte, Mittel- und Neulateinische Philologie",
"6,14": "SSG Klassische Archäologie",
"6,15": "SSG Byzanz",
"6,16": "SSG Neuzeitliches Griechenland",
"6,21": "SSG Ägyptologie",
"6,22": "SSG Alter Orient",
"6,23": "SSG Vorderer Orient inclusive Nordafrika",
"6,231": "SSG Nicht-konventionelles Material aus dem Vorderen Orient",
"6,24": "SSG Südasien",
"6,25": "SSG Ost- und Südostasien",
"6,251": "SSG Nicht-konventionelles Material aus Ost- und Südostasien",
"6,26": "SSG Altaische und paläoasiatische Sprachen und Literaturen",
"6,31": "SSG Afrika südlich der Sahara",
"6,311": "SSG Nicht-konventionelle Materialien aus Afrika",
"6,32": "SSG Ozeanien",
"6,33": "SSG Indianer- und Eskimosprachen und -kulturen",
"7,11": "SSG Allgemeine und vergleichende Sprachwissenschaft, Allgemeine Linguistik",
"7,12": "SSG Allgemeine und vergleichende Literaturwissenschaft",
"7.20": "SSG Germanistik, Deutsche Sprache und Literatur",
"7,22": "SSG Skandinavien",
"7,23": "SSG Benelux",
"7,24": "SSG Anglistik",
"7,25": "SSG Großbritannien und Irland",
"7,26": "SSG Nordamerika",
"7,261": "SSG Noramerikanische Zeitungen",
"7,27": "SSG Keltologie",
"7,29": "SSG Australien, Neuseeland",
"7,30": "SSG Romanistik Allgemeine",
"7,31": "SSG Französische Sprache und Literatur",
"7,32": "SSG Italienische Sprache und Literatur",
"7,34": "SSG Spanien, Portugal",
"7,36": "SSG Ibero-Amerika",
"7,38": "SSG Rumänische Sprache und Literatur",
"7,39": "SSG Slawistik",
"7,41": "SSG Ost-, Ostmittel- und Südosteueropa",
"7,43": "SSG Albanische Sprache und Literatur",
"7,44": "SSG Baltische Länder",
"7,50": "SSG Finno-Ugristik",
"7,51": "SSG Finnland",
"7,52": "SSG Ungarn",
"7,53": "SSG Estnische Sprache  und Literatur",
"7,6": "SSG  Israel",
"7,7": "SSG Judentum",
"8": "SSG Geschichte",
"8,1": "SSG Geschichte Deutschlands, Österreichs und der Schweiz",
"8,2": "SSG Geschichte Frankreichs und Italiens",
"9,10": "SSG Allgemeine Kunstwissenschaft, Mittlere und neuere Kunstgeschichte bis 1945",
"9,11": "SSG Zeitgenössische Kunst ab 1945",
"9,2": "SSG Musikwissenschaft",
"9,3": "SSG Theater- und Filmkunst",
"10": "SSG Volks- und Völkerkunde",
"11": "SSG Allgemeine Naturwissenschaften",
"12": "SSG Biologie",
"13": "SSG Geologie, Mineralogie, Petrologie, Bodenkunde",
"13,1": "SSG Regionale Geologie",
"14": "SSG Geographie",
"14,1": "SSG Veröffentlichungen zur Karthographie",
"15": "SSG Chemie",
"15,3": "SSG Pharmazie",
"16": "SSG Physik",
"16,12": "SSG Astronomie, Astrophysik, Weltraumforschung",
"16,13": "SSG Geophysik",
"16,14": "SSG Metereologie",
"16,15": "SSG Physikalische Ozeanographie",
"17,1": "SSG Reine Mathematik",
"17,2": "SSG Angewandte Mathematik",
"17,3": "SSG Geodäsie und Vermessungswesen",
"18": "SSG Informatik, Datenverarbeitung",
"19": "SSG Ingenieurwissenshaft, Technik",
"19,1": "SSG Bergbau, Markscheidekunde, Hüttenwesen",
"19,2": "SSG Technikgeschichte",
"20": "SSG Architektur, Städtebau, Landesplanung, Raumordnung",
"20,3": "SSG Nichtkonventionelle Materialien zu Städtebau, Landesplanung, Raumordnung aus dem deutschsprachigen Raum",
"21": "SSG Agrarwissenschaften",
"21,3": "SSG Küsten- und Hochseefischerei",
"22": "SSG Veterinärmedizin, Allgemeine Parasitologie",
"23": "SSG Forstwissenschaft",
"24,1": "SSG Informations-, Buch- und  Bibliothekswesen",
"24,2": "SSG Hochschulwesen, Organisation der Wissenschaften und ihrer Einrichtungen",
"25": "SSG Universale wissenschaftliche Zeitschriften",
"26": "SSG Ausländische Zeitungen",
"27": "SSG Parlamentsschriften",
"28,1": "SSG Topographisch Karten",
"28,2": "SSG Thematische Karten",
"28,3": "SSG Seekarten",
"28,4": "SSG Meteorologische und klimatologische Karten",
"30": "SSG Schulbücher",
"31": "SSG Sportwissenschaft",
"AAC": "FID Anglo-American Culture (FID Anglistik / Großbritannien- und Irlandstudien; FID Amerikastudien; FID Kanadastudien; FID Australien- und Neuseelandstudien)",
"ALT": "FID Altertumswissenschaften - Propylaeum",
"ALT-KA": "FID Altertumswissenschaften - Propylaeum",
"ALT-AY": "FID Altertumswissenschaften - Propylaeum",
"AFRIKA": "FID Afrikastudien",
"ASIEN": "FID Asien - CrossAsia",
"AVL": "FID Komparatistik - Allgemeine und Vergleichende Literaturwissenschaft",
"BBI": "FID Buch-, Bibliotheks- und Informationswissenschaft",
"BENELUX": "FID Benelux / Low Countries Studies",
"BIFO": "FID Erziehungswissenschaft und Bildungsforschung",
"BIFO-HF": "FID Erziehungswissenschaft und Bildungsforschung",
"BIODIV": "FID Bio­diversitäts­forschung",
"GEO": "FID Geowissenschaften der festen Erde",
"GER": "FID Germanistik",
"FINNUG": "FID Finnisch-ugrische / uralische Sprachen, Literaturen und Kulturen",
"HIST": "FID Geschichtswissenschaft",
"INTRECHT": "FID internationale und interdisziplinäre Rechtsforschung",
"JUDAICA": "FID Jüdische Studien",
"KARTEN": "FID Kartographie und Geobasisdaten",
"KRIM": "FID Kriminologie",
"KUNST": "FID Kunst, Fotografie, Design - arthistoricum.net",
"Kunst": "FID Kunst, Fotografie, Design - arthistoricum.net",
"LATAM": "FID Lateinamerika, Karibik und Latino Studies",
"LING": "FID Linguistik",
"MATHE": "FID Mathematik",
"MEDIEN": "FID Medien-, Kommunikations- und Filmwissenschaften",
"MONTAN": "FID Montan (Bergbau und Hüttenwesen)",
"MOVE": "FID Mobilitäts- und Verkehrsforschung",
"MUS": "FID Musikwissenschaft",
"NAHOST": "FID Nahost-, Nordafrika- und Islamstudien",
"NORD": "FID Nordeuropa",
"OST": "FID Ost-, Ostmittel- und Südosteuropa",
"PHARM": "FID Pharmazie",
"PHILOS": "FID Philosophie",
"POL": "FID Politik­wissenschaft",
"REWI": "FID Religionswissenschaft",
"ROM": "FID Romanistik",
"SKA": "FID Sozial- und Kulturanthropologie",
"SLAW": "FID Slawistik",
"SOZIO": "FID Soziologie",
"THEATER": "FID Darstellende Kunst",
"THEO": "FID Theologie",
"ZENTRALASIEN": "FID Zentralasien - Autochthone Kulturen und Sprachen"
}

lookup_coll = {
"AUGU": "Augustinus-Literaturdatenbank Würzburg",
"BA": "Bibliotheken der Aufklärungszeit",
"BGTS": "Bibliographie Geschichte der Technik (Vergabe durch die SLUB Dresden)",
"BIDL": "Mikrofiche-Ausgabe der \"Bibliothek der Deutschen Literatur\"",
"BIIN": "Bibelwissenschaftliche Literaturdokumentation Innsbruck (IxTheo)",
"BIST": "Mikrofiche-Ausgabe der \"Bibliothek Stein\"",
"CeDi": "Centralasia Digital",
"CICO": "Mikrofiche-Ausgabe der \"Cicognara Library\"",
"DAKR": "Datenbank Kanonisches Recht Münster",
"DTH5": "Aufsätze und Rezensionen aus dem Digitalisierungsprojekt theologischer Zeitschriften DigiTheo_5",
"EDCO": "Mikrofiche-Ausgabe der \"Edition Corvey\"",
"FOOD": "Food studies",
"GIRA": "Literaturdokumentation zur Mimetischen Theorie von René Girard Innsbruck",
"HistGuide": "History Guide: Fachkatalog digitaler Ressourcen für die Geschichtswissenschaft",
"INKA": "Daten übernommen aus dem Inkunabelkatalog deutscher Bibliotheken (INKA)",
"KALD": "Kanonistische Literaturdokumentation Innsbruck (IxTheo)",
"KLOK": "Kulturrat Oldenburg Karten",
"krex": "Manueller Eintrag bei maschinell selektierten Datensätzen für KrimDok, die keinen kriminologischen Bezug haben",
"leos": "In LEO-BW verwendet",
"MIKA": "Missionsbibliothek und katholische Dokumentationsstelle des MWI Aachen (IxTheo)",
"MENAdoc": "Fachinformationsdienst Nahost-, Nordafrika- und Islamstudien der Universitäts- und Landesbibliothek Sachsen-Anhalt (Halle)",
"mkri": "Fachinformationsdienst Kriminologie",
"mteo": "Theologische und religionswiss. Titel, maschinell gekennzeichnet",
"OERR": "Open educational resources Repositorium",
"PAHA": "Palatina-Handschrift",
"PALA": "Mikrofiche-Ausgabe der \"Bibliotheca Palatina\"",
"PZ": "Pommersche Zeitungen/Zeitschriften",
"redo": "Religionswissenschaft/Dokumentationsstelle",
"SAVE": "Sicherung des audiovisuellen Erbes in Sachsen",
"SAXB": "Titel aus der Sächsischen Bibliographie (Vergabe durch die SLUB Dresden)",
"SP": "Sammlung Perthes",
"VDLN": "Verteilte digitale Landesbibliothek Niedersachsen",
"WABU": "Mikrofiche-Ausgabe der \"Edition St. Walburg\" (Frauenklosterbibliothek St. Walburg)",
"WLMMA": "Wolfgang Laade Music of Man Archive",
}
